### ISSUE TITLE
Question about the result on one program

### ISSUE THREAD

**Issue by shaobo-he** [seahorn/sea-dsa#54]
Hello SeaDsa developers,

Sorry to bother you again. I also attempted to use SeaDsa (the llvm-8.0 branch) on another program (this time I compiled it with -O0) and the resulting graphs seem spurious, too. For example,

```C
#include <assert.h> 

int* A;

typedef struct {
  int* a;
  long b;
} S;

S foo() {
  S x = {A, 2L};
  assert(1);
  return x;
}

int main() {
  int a = 1;
  A = &a;
  S y = foo();
  assert(*(y.a) == 1);
  return 0;
}
```

The graph is obtained using the following commands,

```bash
clang -O0 -c -emit-llvm -S test2.c
~/sea-dsa/build/run/bin/seadsa -sea-dsa=butd-cs -sea-dsa-type-aware -sea-dsa-dot test2.ll  -sea-dsa-dot-outdir=test2
(cd test2 ; dot -Tpdf main.mem.dot -o main.mem.pdf)
```

[main.mem.pdf](https://github.com/seahorn/sea-dsa/files/3821980/main.mem.pdf)

It seems `*A` and the pointer extracted from the return value of `foo` point to different memory objects. If I understand it correctly, they should point to the same object.

Please let me know if I missed anything or this is expected or not.

**Comment by caballa** [comment]
Hi Shaobo, 
Thanks for reporting this problem. We have committed a fix for it. Please, update sea-dsa and try again.

**Comment by shaobo-he** [comment]
Thank you for your prompt patch for this issue. I can confirm the example in this issue is fixed, however, I noticed you referenced #53 in your fix, but when I compile with `-01` on that example I am still seeing the issue.

**Comment by shaobo-he** [comment]
Is it possible get sea-dsa to generate a unified view of a whole program (e.g., all DSA nodes) from a given function?
For example, if functions `foo` and `bar` both access the same memory object, is it possible to see them both referring to that object.

**Comment by agurfinkel** [comment]
Yes. This is context insensitive result. There is a flag to compute one DSAGraph for all the functions.
